language: python
python:
  - "2.7"
install:
  - make deps
script:
  - make lint
  - make test_xunit
  - make docker_build
  - make docker_run
  - sleep 3; make test_api
after_success:
  - make docker_build
  - make docker_push
deploy:
  provider: heroku
  app: protected-ridge-47688
  api_key: ${HEROKU_API_KEY}
