language: python
python:
  - "2.7"
install:
  - make deps
script:
  - make test
after_success:
  - make docker_build
  deploy:
    provider: heroku
    app: protected-ridge-47688
    api_key: ${HEROKU_API_KEY}
